services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: pricing_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Warsaw
    ports: # host_port:container_port
      - "54321:5432"
    volumes: #host_volume:container_volume
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - pricing_network

  # Airflow
  airflow-standalone:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: pricing_airflow
    depends_on: # postgres must be activated first
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__CORE_AIRFLOW_HOME=/opt/airflow
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_ADMIN_USER}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RUNNING_IN_DOCKER=true
      - PYTHONPATH=/opt/airflow/src
      - TZ=Europe/Warsaw
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: standalone # run airflow's all basic functions
    networks:
      - pricing_network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: pricing_dashboard
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PYTHONPATH=/app/src
      - RUNNING_IN_DOCKER=true
      - TZ=Europe/Warsaw
    volumes:
      - ./src:/app/src
    command: >
      python3 -m streamlit run /app/src/ui/app.py 
      --server.port=8501 
      --server.address=0.0.0.0 
    networks:
      - pricing_network

  tor-proxy: # UNUSED
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: pricing_tor_proxy
    environment:
      - TOR_PASSWORD=${TOR_PASSWORD}
      - TZ=Europe/Warsaw
    ports:
      - "9050:9050" # SOCKS5 port
      - "9051:9051" # control port
    networks:
      - pricing_network

  vpn-gateway:
    image: qmcgaw/gluetun
    container_name: pricing_vpn_gateway
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - WIREGUARD_MTU=1280
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - PROXY_SOCKS5_LISTEN_ADDRESS=:1080
      - PROXY_SOCKS5_ENABLED=yes
      - HTTPPROXY=on
      - HTTPPROXY_LISTEN_ADDRESS=:8888
      - TZ=Europe/Warsaw
    ports:
      - "55501:1080"
      - "55502:8888"
    networks:
      - pricing_network

volumes:
  postgres_data:

networks:
  pricing_network:
    driver: bridge