FROM python:3.11-slim

RUN useradd -m -u 1000 appuser
WORKDIR /app

# dla postgresa...
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER appuser
EXPOSE 8501