import streamlit as st

################
# WEBPAGE CODE #
################
st.header("📋 Execution Logs")
st.divider()
st.markdown("This menu allows you to view and filter system execution logs.")
st.markdown("Listed below are all the logs generated by this application while running its processes.")
st.divider()